# Site
title: 'บอร์ดแล้วบ่น'
description: 'บ่นเรื่อยเปื่อยเรื่องเกมกระดานเป็นส่วนมาก'
logo: 'assets/images/logo_long.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: ''
email: 'kong.sisada@gmail.com'
# mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 9
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

authors:
    sisada:
      listname:       sisada
      name:           Sisada Ransibrahmanakul
      site:           https://www.facebook.com/boardnbon
      avatar:         assets/images/avatar1.jpg
      bio:            "โปรแกรมเมอร์ขี้บ่นที่ชอบเล่นเกมกระดาน"
      email:          kong.sisada@gmail.com
      facebook:       https://www.facebook.com/PrinceFrogOobOob/

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]